[[PGPLOT]]
arch = "aarch64"
git-tree-sha1 = "bc2b3c9723e87ff22c9d546ae36a09641cdc6a05"
libgfortran_version = "5.0.0"
os = "macos"

    [[PGPLOT.download]]
    sha256 = "805ff99c1e1bb7b1176b7b353f658ceb02e7821d0516075390b854fae0ac9ef7"
    url = "https://github.com/JuliaBinaryWrappers/PGPLOT_jll.jl/releases/download/PGPLOT-v5.2.2+0/PGPLOT.v5.2.2.aarch64-apple-darwin-libgfortran5.tar.gz"
[[PGPLOT]]
arch = "i686"
git-tree-sha1 = "0c2b63c506b61508bc3af489f9aa9abe3d4ab7cb"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PGPLOT.download]]
    sha256 = "2476552a1856d43804869a6e504b71ab83b2cd047e6be79943abe618a758ae0e"
    url = "https://github.com/JuliaBinaryWrappers/PGPLOT_jll.jl/releases/download/PGPLOT-v5.2.2+0/PGPLOT.v5.2.2.i686-linux-gnu-libgfortran3.tar.gz"
[[PGPLOT]]
arch = "i686"
git-tree-sha1 = "4863af73d8d78e9a5467c8f3490294dba3b2c351"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PGPLOT.download]]
    sha256 = "fbfc307c802c5b2b0f2731ef92f342db1b24e216f2353f33bee7185725d8ba07"
    url = "https://github.com/JuliaBinaryWrappers/PGPLOT_jll.jl/releases/download/PGPLOT-v5.2.2+0/PGPLOT.v5.2.2.i686-linux-gnu-libgfortran4.tar.gz"
[[PGPLOT]]
arch = "i686"
git-tree-sha1 = "a9fa313e011d424bb0a3e2e7eb32ce9e013d02cf"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PGPLOT.download]]
    sha256 = "e01438cecf5e255cf942fb864f7d091a156d0fc5e6e9c299018189b848298241"
    url = "https://github.com/JuliaBinaryWrappers/PGPLOT_jll.jl/releases/download/PGPLOT-v5.2.2+0/PGPLOT.v5.2.2.i686-linux-gnu-libgfortran5.tar.gz"
[[PGPLOT]]
arch = "x86_64"
git-tree-sha1 = "68c17467fdcaded75e7d3e196560f49b4519d6dc"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PGPLOT.download]]
    sha256 = "7f550ade1f48ebf5e3f3d9d9b19baa3bd2bb974ca669c2f664191d6964e09d01"
    url = "https://github.com/JuliaBinaryWrappers/PGPLOT_jll.jl/releases/download/PGPLOT-v5.2.2+0/PGPLOT.v5.2.2.x86_64-linux-gnu-libgfortran3.tar.gz"
[[PGPLOT]]
arch = "x86_64"
git-tree-sha1 = "6af7f7255ccc12d213fb83e24cc09fed02b6b2e2"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PGPLOT.download]]
    sha256 = "fa08b4e1cc83786316ab152f037238a099f99e6874c1990383e320d8c4ec42c8"
    url = "https://github.com/JuliaBinaryWrappers/PGPLOT_jll.jl/releases/download/PGPLOT-v5.2.2+0/PGPLOT.v5.2.2.x86_64-linux-gnu-libgfortran4.tar.gz"
[[PGPLOT]]
arch = "x86_64"
git-tree-sha1 = "97d850aea9eb00bb59fd2026ec82fb777d53b27b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PGPLOT.download]]
    sha256 = "1073985a46f3f78391893bda5bf0f9552aca5677f5118e888497ec0563c62f4f"
    url = "https://github.com/JuliaBinaryWrappers/PGPLOT_jll.jl/releases/download/PGPLOT-v5.2.2+0/PGPLOT.v5.2.2.x86_64-linux-gnu-libgfortran5.tar.gz"
[[PGPLOT]]
arch = "x86_64"
git-tree-sha1 = "4bc83cf122708943527fb766557f5ae1380d2911"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PGPLOT.download]]
    sha256 = "bd2ba8d3f18b904ac6176d8b3af24879991ef89d7b19bb78fb0477fc7812b42f"
    url = "https://github.com/JuliaBinaryWrappers/PGPLOT_jll.jl/releases/download/PGPLOT-v5.2.2+0/PGPLOT.v5.2.2.x86_64-linux-musl-libgfortran3.tar.gz"
[[PGPLOT]]
arch = "x86_64"
git-tree-sha1 = "074229d1c9f42e7a0fc7d078a2c67fb735a79a1f"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PGPLOT.download]]
    sha256 = "2e3f5c50225836a15005b478c0554dce6138ca84e51fd279dc7de18b07efd881"
    url = "https://github.com/JuliaBinaryWrappers/PGPLOT_jll.jl/releases/download/PGPLOT-v5.2.2+0/PGPLOT.v5.2.2.x86_64-linux-musl-libgfortran4.tar.gz"
[[PGPLOT]]
arch = "x86_64"
git-tree-sha1 = "970cc6de765b930cfb67daac545e98fc857f7913"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PGPLOT.download]]
    sha256 = "3bdc93af71fd0af8b4a5e9cc00dbbca399c27df2d9c415886e78695ce1241777"
    url = "https://github.com/JuliaBinaryWrappers/PGPLOT_jll.jl/releases/download/PGPLOT-v5.2.2+0/PGPLOT.v5.2.2.x86_64-linux-musl-libgfortran5.tar.gz"
