# Autogenerated wrapper script for PGPLOT_jll for aarch64-apple-darwin-libgfortran5
export libpgplot

using CompilerSupportLibraries_jll
using libpng_jll
JLLWrappers.@generate_wrapper_header("PGPLOT")
JLLWrappers.@declare_library_product(libpgplot, "@rpath/libpgplot.dylib")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, libpng_jll)
    JLLWrappers.@init_library_product(
        libpgplot,
        "lib/libpgplot.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
